# Default values for solr.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
image: "solr"
imagePullPolicy: "Always"
command: "[\"solr\"]"
args: "[\"-f\", \"-c\", \"-m\", \"16g\", \"-z\", \"zk-0.zk-hs.default.svc.cluster.local:2181,zk-1.zk-hs.default.svc.cluster.local:2181,zk-2.zk-hs.default.svc.cluster.local:2181\"]"
replicas: 4
minAvailable: 3
containerPort: 8983
resources:
  requests:
    cpu: 2 
    memory: "16Gi"
  limits:
    cpu: 4 
    memory: "16Gi"
heap: "16G"
storage: "50Gi"
storageClass: solr-data 
tickTimeMs: 2000
initTicks: 10
syncTicks: 5
clientCnxns: 60
snapRetain: 3
purgeHours: 1
probeInitialDelaySeconds: 15
probeTimeoutSeconds: 5
antiAffinity: "hard"
logLevel: "INFO"
security:
  enabled: false 
  runAsUser: 1000
  fsGroup: 1000
