help :
	clear
	@echo "--------------------------------------------------------------------------------------------------------"
	@echo " Solr Spark Showcase"
	@echo "--------------------------------------------------------------------------------------------------------"
	@echo " usage: make <target>"
	@echo " valid targets are:"
	@echo "                   "
	@echo " Tasks             "
	@echo " =============     "
	@echo " - install         "
	@echo " - clean           "
	@echo " - start          "
	@echo " - stop          "
	@echo "--------------------------------------------------------------------------------------------------------"

install: setup-nodes.sh

clean:
	echo TODO

start:
	start-nodes.sh

stop:
	stop-nodes.sh
