---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: solr-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: solr.local
    http:
      paths:
      - path: /
        backend:
          serviceName: solr-solr
          servicePort: 8983
